trigger:
  branches:
    include:
      - main
  paths:
    include:
      - FleetManagement.Equipment/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: FleetManagement_Infrastructure

steps:
- task: Docker@2
  displayName: "Build and Push Equipment Microservice"
  inputs:
    containerRegistry: '$(fm_docker_hub_service_connection_name)'
    repository: '$(fm_docker_repository_equipment)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/FleetManagement.Equipment/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/FleetManagement.Equipment'
    tags: |
      $(Build.BuildId)
      latest
